import json
import sys
import os
import datetime
import pytest

def load_plan(plan_path):
    with open(plan_path, 'r') as f:
        return json.load(f)

def generate_summary(plan, suite_results, reports_dir):
    """Create a master HTML page linking to all suite reports."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    run_id = plan["run_id"]
    target = plan["target"]["endpoint"]

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AI Quality Report - {run_id}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        tr:hover {{ background-color: #f5f5f5; }}
        .pass {{ color: green; font-weight: bold; }}
        .fail {{ color: red; font-weight: bold; }}
        .warn {{ color: orange; font-weight: bold; }}
        .summary {{ background: #f9f9f9; padding: 20px; border-radius: 8px; margin: 20px 0; }}
    </style>
</head>
<body>
    <h1>AI Quality Operations Report</h1>
    <div class="summary">
        <p><strong>Run ID:</strong> {run_id}</p>
        <p><strong>Target:</strong> {target}</p>
        <p><strong>Date:</strong> {now}</p>
    </div>
    <h2>Suite Results</h2>
    <table>
        <tr>
            <th>Suite</th>
            <th>Status</th>
            <th>Detailed Report</th>
        </tr>
"""

    overall_pass = True
    for suite_name, result in suite_results.items():
        if result == 0:
            status = "PASS"
        elif result == 5:
            status = "WARN"
        else:
            status = "FAIL"
            overall_pass = False

        report_file = f"{suite_name}.html"
        html += f"""
        <tr>
            <td>{suite_name}</td>
            <td class="{status.lower()}">{status}</td>
            <td><a href="{report_file}" target="_blank">Open Report</a></td>
        </tr>"""

    html += f"""
    </table>
    <h2>Overall Verdict: <span class="{'pass' if overall_pass else 'fail'}">{'PASS' if overall_pass else 'FAIL'}</span></h2>
    <p><em>Generated by AI Quality Ops Platform</em></p>
</body>
</html>"""

    summary_path = os.path.join(reports_dir, "summary.html")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"\n📄 Master report saved: {summary_path}")

def run_plan(plan):
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)

    exit_code = 0
    suite_results = {}

    for suite in plan["suites"]:
        suite_name = suite["name"]
        suite_path = suite["path"]
        blocking = suite["blocking"]

        print(f"\n===== Running suite: {suite_name} =====")

        report_path = os.path.join(reports_dir, f"{suite_name}.html")
        result = pytest.main([
            suite_path,
            "-q",
            "--tb=short",
            "--disable-warnings",
            f"--html={report_path}",
            "--self-contained-html"
        ])

        suite_results[suite_name] = result

        if result == 5:
            print(f"⚠️  Suite '{suite_name}' has no tests – skipping.")
        elif result != 0 and blocking:
            print(f"🚨 Blocking suite '{suite_name}' FAILED. Aborting run.")
            generate_summary(plan, suite_results, reports_dir)
            sys.exit(1)

        exit_code = exit_code or result

    generate_summary(plan, suite_results, reports_dir)
    return exit_code

if __name__ == "__main__":
    plan_path = sys.argv[1] if len(sys.argv) > 1 else os.getenv("TEST_PLAN", "test_plans/sample_plan.json")
    plan = load_plan(plan_path)
    print(f"Running plan: {plan['run_id']} against {plan['target']['endpoint']}")
    code = run_plan(plan)
    sys.exit(code)